name: your_app_name
description: "Your app description"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  # Core Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_analytics: ^10.8.0
  firebase_messaging: ^14.7.10

  # State Management & DI
  provider: ^6.1.1
  get_it: ^7.6.7

  # Network & Storage
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  http: ^1.2.2

  # UI Components
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  fl_chart: ^0.70.1
  webview_flutter: ^4.10.0
  cached_network_image: ^3.3.1
  pull_to_refresh: ^2.0.0
  image_picker: ^1.0.7

  # Authentication
  google_sign_in: ^6.2.1

  # Utilities
  intl: ^0.18.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
